name: rvaeeeg_py310
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lmdb=0.9.31
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - acres==0.5.0
      - aiobotocore==2.24.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - axial-positional-embedding==0.3.12
      - bids-validator==1.14.7.post0
      - bidsschematools==1.1.0
      - botocore==1.40.18
      - braindecode==1.2.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colt5-attention==0.11.1
      - contourpy==1.3.2
      - coverage==7.10.7
      - cycler==0.12.1
      - dnspython==2.8.0
      - docopt==0.6.2
      - docstring-inheritance==2.2.2
      - edfio==0.4.10
      - edflib-python==1.0.8
      - eegdash==0.3.8
      - eeglabio==0.1.2
      - einops==0.8.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - formulaic==1.2.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - geoopt==0.5.1
      - greenlet==3.2.4
      - h5io==0.2.5
      - h5py==3.14.0
      - hyper-connections==0.2.1
      - idna==3.10
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linear-attention-transformer==0.19.1
      - linformer==0.2.3
      - llvmlite==0.45.1
      - local-attention==1.11.2
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - memory-profiler==0.61.0
      - mne==1.10.1
      - mne-bids==0.17.0
      - moabb==1.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.7.0
      - nbformat==5.10.4
      - networkx==3.4.2
      - nibabel==5.3.2
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.3
      - pathlib-abc==0.5.1
      - pillow==11.3.0
      - plotly==6.3.1
      - pooch==1.8.2
      - product-key-memory==0.2.11
      - propcache==0.4.0
      - pybids==0.20.0
      - pycparser==2.23
      - pymatreader==1.1.0
      - pymongo==4.15.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyriemann==0.7
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - s3fs==2025.9.0
      - scikit-learn==1.5.2
      - seaborn==0.12.2
      - skorch==1.2.0
      - soundfile==0.13.1
      - sqlalchemy==2.0.43
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchinfo==1.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - universal-pathlib==0.3.2
      - urllib3==1.26.20
      - wfdb==4.3.0
      - wrapt==1.17.3
      - xarray==2023.12.0
      - xmltodict==1.0.2
      - yarl==1.22.0
